---
title: "Figure3S"
author: "Aina Rill-Hinarejos"
date: "2023-07-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```

# Introduction

This is the code to reproduce **Figure 3S Additional longitudinal and repertoire analysis of T cells across timepoints.**: Fig3S C-H.
To obtain the data object used in this notebook, please run **01_TCR_Data_Analysis.Rmd**.


## Package loading

```{r}
library(gdata)
library(Seurat)
library(reshape2)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(scRepertoire)
library(circlize)
library(Startrac)
library(stringr)
library(plyr)
library(dplyr)
library(ggh4x)
library(ggbeeswarm)
library(monocle)
````

## Loading colors

```{r}
cols_patient =c("Patient 1"= "aquamarine", "Patient 2"="lightpink", "Patient 3"="yellow1", "Patient 4"="skyblue", "Patient 5"="sienna1")
cols_patient2 <- c("aquamarine", "#6FDFBA", "lightpink", "#DF9FA9", "yellow1", "#DFDC00", "skyblue", "#76B4CF","sienna1", "#DF733E")
cols_timepoint<- c("IP"="#4E6AAB","Peak"="#e78ac3")
cols_anno <- c("CD4+ Naive T cells"= "#33A02C",
                     "CD4+ CEntral/Effector memory T cells (CM/EM)"="#B2DF8A",
                     "CD8+ cytotoxic T cells"="#185B88",
                     "CD8+ Effector T cells (E)"="#1F78B4",
                     "CD8+ Eff/Mem T cells (EM)"="#A6CEE3",
                     "Early prolif: MCM3/5/7+ PCNA+ T cells"="#FB9A99",
                     "Late prolif: histones enriched MKI67+ T cells"="#E31A1C",
                     "Late prolif: CCNB1/2+ CDK1+ T cells"="#CAB2D6", 
                     "Late prolif: STMN1+ BIRC5+"="#FDBF6F",
                     "Ribosomal/Mitochondrial/Degraded cells"="#FF7F00",
                     "gamma-delta T cells"="#6A3D9A")
strip <- strip_themed(background_x = elem_list_rect(fill = c("#A6CEE3", "#1F78B4","#185B88", "#B2DF8A","#33A02C", "#CAB2D6", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00" )))
col_clono <- c("Hyperexpanded (100 < X <= 500)"="#810F7C", "Large (20 < X <= 100)"="#8856A7","Medium (5 < X <= 20)"= "#8C96C6","Small (1 < X <= 5)"= "#9EBCDA", "Single (0 < X <= 1)"="#BFD3E6", "No clonotype detected"="gray69")
````

## Data import

```{r}
combined_infusion <- readRDS("../data/combined_files/combined_infusion_CARPOS.rds")
combined_infusion<- addVariable(combined_infusion, variable.name  = "patient", 
                variables = c("patient1", "patient2","patient3", "patient4","patient5"))
table_combined_infusion<- clonalDiversity(combined_infusion, 
                cloneCall = "gene", 
                group.by = "sample", 
                n.boots = 100, exportTable = T) #diversity_infusion
````

```{r}
combined_peak <- readRDS("../data/combined_files/combined_peak_CARPOS.rds")
combined_peak<- addVariable(combined_peak, variable.name = "patient", 
                variables = c("patient1", "patient2","patient3", "patient4","patient5"))
table_combined_peak<- clonalDiversity(combined_peak, 
                cloneCall = "gene", 
                group.by = "sample", 
                n.boots = 100, exportTable = T) #diversity_peak
````

```{r}
table_combined_infusion$timepoint <- "Infusion"
table_combined_peak$timepoint <- "Peak"

table_combined_infusion$patient <- c("Patient 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5")
table_combined_peak$patient <- c("Patient 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5")

table_combined <- rbind(table_combined_infusion,table_combined_peak)
table_combined$sample <- factor(table_combined$sample)
````



```{r}
seurat <- readRDS("../data/MENENDEZ_DEF.rds")
seurat_carneg <- subset(seurat, subset = Class1 == "CAR-")
seurat_carpos <- subset(seurat, subset = Class1 == "CAR+")

seurat_carneg <- subset(seurat_carneg, subset = cloneSize != "No clonotype detected")
seurat_carneg <- subset(seurat_carneg, subset = cloneSize != "Single (0 < X <= 1)")
seurat_carneg_nogd <- subset(seurat_carneg, subset = annotation != "gamma-delta T cells")

seurat_carpos <- subset(seurat_carpos, subset = cloneSize != "No clonotype detected")
seurat_carpos <- subset(seurat_carpos, subset = cloneSize != "Single (0 < X <= 1)")
seurat_carpos_nogd <- subset(seurat_carpos, subset = annotation != "gamma-delta T cells")

seurat_carneg_IP <- subset(seurat_carneg_nogd, subset = Timepoint == "IP")
seurat_carneg_PEAK <- subset(seurat_carneg_nogd, subset = Timepoint == "Peak")
````

```{r}
data_pt1 <- subset(seurat_carpos_nogd, subset = Patient_id == "patient1")
data_pt1_I <- subset(data_pt1, subset = Timepoint == "IP")
data_pt1_P <- subset(data_pt1, subset = Timepoint == "Peak")

data_pt2 <- subset(seurat_carpos_nogd, subset = Patient_id == "patient2")
data_pt2_I <- subset(data_pt2, subset = Timepoint == "IP")
data_pt2_P <- subset(data_pt2, subset = Timepoint == "Peak")

data_pt3 <- subset(seurat_carpos_nogd, subset = Patient_id == "patient3")
data_pt3_I <- subset(data_pt3, subset = Timepoint == "IP")
data_pt3_P <- subset(data_pt3, subset = Timepoint == "Peak")

data_pt4 <- subset(seurat_carpos_nogd, subset = Patient_id == "patient4")
data_pt4_I <- subset(data_pt4, subset = Timepoint == "IP")
data_pt4_P <- subset(data_pt4, subset = Timepoint == "Peak")

data_pt5 <- subset(seurat_carpos_nogd, subset = Patient_id == "patient5")
data_pt5_I <- subset(data_pt5, subset = Timepoint == "IP")
data_pt5_P <- subset(data_pt5, subset = Timepoint == "Peak")
````

```{r}
data2<- readRDS("../data/dataordered_V2.rds")
````


## Plot Fig3S C

```{r}
occRep_ip<-clonalOccupy(seurat_carneg_IP, x.axis = "annotation", exportTable =T)
occRep_peak <-clonalOccupy(seurat_carneg_PEAK, x.axis = "annotation", exportTable =T)

occRep_ip$Timepoint <- "IP"
occRep_peak$Timepoint <- "PEAK"

occRep <- rbind(occRep_ip, occRep_peak)
occRep$annotation <- factor(occRep$annotation, levels = 
                                    c("CD8+ Eff/Mem T cells (EM)", 
                                      "CD8+ Effector T cells (E)", 
                                      "CD8+ cytotoxic T cells", 
                                      "CD4+ CEntral/Effector memory T cells (CM/EM)", 
                                      "CD4+ Naive T cells", "gamma-delta T cells", 
                                      "Late prolif: CCNB1/2+ CDK1+ T cells", 
                                      "Early prolif: MCM3/5/7+ PCNA+ T cells", 
                                      "Late prolif: histones enriched MKI67+ T cells", 
                                      "Late prolif: STMN1+ BIRC5+",
                                      "Ribosomal/Mitochondrial/Degraded cells"))
occRep$cloneSize <- factor(occRep$cloneSize, levels = c("Small (1 < X <= 5)", "Medium (5 < X <= 20)", "Large (20 < X <= 100)", "Hyperexpanded (100 < X <= 500)"))


 # Draw barplot with grouping & stacking
ggplot(occRep, aes(x = Timepoint, y = n, fill = cloneSize)) + 
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(~ annotation) +
  scale_fill_manual(values = col_clono) + facet_grid2(~ annotation, strip = strip) +
  theme(strip.text = element_text(colour = NA),
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))
````

## Plot Fig3S D

```{r}
I <- getCirclize(data_pt1_I, group.by = "annotation")
I<-chordDiagram(I, self.link = 1, grid.col =cols_anno , annotationTrack = c("grid", "axis"))
title("IP Patient 1")

P <- getCirclize(data_pt1_P, group.by = "annotation")
P<-chordDiagram(P, self.link = 1, grid.col =cols_anno, annotationTrack = c("grid", "axis") )
title("Peak Patient 1")
````
```{r}
I <- getCirclize(data_pt2_I, group.by = "annotation")
I<-chordDiagram(I, self.link = 1, grid.col =cols_anno , annotationTrack = c("grid", "axis"))
title("IP Patient 2")

P <- getCirclize(data_pt2_P, group.by = "annotation")
P<-chordDiagram(P, self.link = 1, grid.col =cols_anno, annotationTrack = c("grid", "axis") )
title("Peak Patient 2")
````

```{r}
I <- getCirclize(data_pt3_I, group.by = "annotation")
I<-chordDiagram(I, self.link = 1, grid.col =cols_anno , annotationTrack = c("grid", "axis"))
title("IP Patient 3")

P <- getCirclize(data_pt3_P, group.by = "annotation")
P<-chordDiagram(P, self.link = 1, grid.col =cols_anno, annotationTrack = c("grid", "axis") )
title("Peak Patient 3")
````

```{r}
I <- getCirclize(data_pt4_I, group.by = "annotation")
I<-chordDiagram(I, self.link = 1, grid.col =cols_anno , annotationTrack = c("grid", "axis"))
title("IP Patient 4")

P <- getCirclize(data_pt4_P, group.by = "annotation")
P<-chordDiagram(P, self.link = 1, grid.col =cols_anno, annotationTrack = c("grid", "axis") )
title("Peak Patient 4")
````

```{r}
I <- getCirclize(data_pt5_I, group.by = "annotation")
I<-chordDiagram(I, self.link = 1, grid.col =cols_anno , annotationTrack = c("grid", "axis"))
title("IP Patient 5")

P <- getCirclize(data_pt5_P, group.by = "annotation")
P<-chordDiagram(P, self.link = 1, grid.col =cols_anno, annotationTrack = c("grid", "axis") )
title("Peak Patient 5")
````

## Plot Fig3S E

```{r}
text <- element_text(color = "black", size = 16)
text.lab <- element_text(color = "black", size = 12)
text.lab2 <- element_text(color = "black", size = 10)
text.lab3 <- element_text(color = "black", size = 9)

aux_df <- data.frame(barcodes=colnames(data2),idents=data2$annotation,Pseudotime=data2$Pseudotime, Timepoint = data2$Timepoint)

ident_trajectory <- ggplot(aux_df,aes(x=idents,y=Pseudotime,col=Timepoint)) +
  geom_quasirandom(alpha=.8) + coord_flip() + theme_classic() +
  scale_color_manual(values=cols_timepoint) + theme(text = element_text(size = 14)) 

ident_trajectory
````


## Plot Fig3S F

```{r}
ordering.genes <- VariableFeatures(seurat)
marker_genes <- row.names(subset(fData(data2),
                   gene_short_name %in% ordering.genes))
data2 <- reduceDimension(data2,
                         max_components = 2,
                         norm_method = 'log',
                         num_dim = 3,
                         reduction_method = 'tSNE',
                         verbose = T)
data2 <- clusterCells(data2, verbose = F, num_clusters = 10)
````
````{r}
diff_test_res <- differentialGeneTest(data2[marker_genes,],
                                      fullModelFormulaStr = "~sm.ns(Pseudotime)",
                                      cores=4)
sig_gene_names <- row.names(subset(diff_test_res, qval < 0.000000000000000000000000000000000000001))
````
```{r}
sig_gene_names <- unique(c("STMN1", "CDC20", "HIST2H2BF", "UBE2C", "GNLY", "GZMK", "CCNB1", "MKI67", "KLRG1", "KLRB1", "CD69", "GZMH", "HMGB1", "PCNA","GZMB", "IFITM1", "CD27", "LAG3", "MKI67", "TOP2A", "CDK1", "CXCR3", "GZMK", "NKG7", "HSPA1A", "HSPA1B", "PRF1", "TRDV1", "TRGV2" ))
plot_pseudotime_heatmap(data2[sig_gene_names,],
                num_clusters = 3,
                cores = 1,
                show_rownames = T,
                hmcols = colorRampPalette(colors = c("blue", "white", "red"))(62))
````



## Plot Fig3S G

```{r}
cols2=c("CD4+ CEntral/Effector memory T cells (CM/EM)"="white",
               "CD4+ Naive T cells"="white",
               "CD8+ cytotoxic T cells"="#185B88",
               "CD8+ Eff/Mem T cells (EM)"="white",
               "CD8+ Effector T cells (E)"="white",
               "Early prolif: MCM3/5/7+ PCNA+ T cells"="white",
               "Late prolif: CCNB1/2+ CDK1+ T cells"="white",
               "Late prolif: histones enriched MKI67+ T cells"="white",
               "Late prolif: STMN1+ BIRC5+"="white",
               "Ribosomal/Mitochondrial/Degraded cells"="white")
data_pt1 <- subset(seurat_carneg_nogd, subset = Patient_id == "patient1")
data_pt2 <- subset(seurat_carneg_nogd, subset = Patient_id == "patient2")
data_pt3 <- subset(seurat_carneg_nogd, subset = Patient_id == "patient3")
data_pt4 <- subset(seurat_carneg_nogd, subset = Patient_id == "patient4")
data_pt5 <- subset(seurat_carneg_nogd, subset = Patient_id == "patient5")


pt1 <-alluvialClones(data_pt1, cloneCall = "CTstrict", 
                   y.axes = c("annotation", "cloneType", "Timepoint"), 
                   color = "annotation") + scale_fill_manual(values=cols2)+theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 1650))
pt2 <-alluvialClones(data_pt2, cloneCall = "CTstrict", 
                   y.axes = c("annotation", "cloneType", "Timepoint"), 
                   color = "annotation") + scale_fill_manual(values=cols2)+theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 1650))
pt3 <-alluvialClones(data_pt3, cloneCall = "CTstrict", 
                   y.axes = c("annotation", "cloneType", "Timepoint"), 
                   color = "annotation") + scale_fill_manual(values=cols2)+theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 1650))
pt4 <-alluvialClones(data_pt4, cloneCall = "CTstrict", 
                   y.axes = c("annotation", "cloneType", "Timepoint"), 
                   color = "annotation") + scale_fill_manual(values=cols2)+theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 1650))
pt5 <-alluvialClones(data_pt5, cloneCall = "CTstrict", 
                   y.axes = c("annotation", "cloneType", "Timepoint"), 
                   color = "annotation") + scale_fill_manual(values=cols2)+theme(legend.position = "none") + scale_y_continuous(limits = c(0, 1650))

ggarrange(pt1 + facet_grid(. ~"Patient 1"), 
          pt2 + 
               theme(axis.text.y = element_blank(),
                     axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     plot.margin = margin(r = 1, l = 1) )+ facet_grid(. ~"Patient 2"),
          pt3 + 
               theme(axis.text.y = element_blank(),
                     axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     plot.margin = margin(r = 1, l = 1) )+ facet_grid(. ~"Patient 3"), 
          pt4 + 
               theme(axis.text.y = element_blank(),
                     axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     plot.margin = margin(r = 1, l = 1) )+ facet_grid(. ~"Patient 4"), 
          pt5 + 
               theme(axis.text.y = element_blank(),
                     axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     plot.margin = margin(r = 1, l = 1) )+ facet_grid(. ~"Patient 5"),  align = "hv", ncol=5)

```




## Plot Fig3S H

```{r}
seurat_carpos <- subset(seurat, subset = Class1 == "CAR+")

table_unique_clono <- scRepertoire:::.expression2List(seurat_carpos, split.by = "Sample_id")
table_unique_clono <-clonalQuant(table_unique_clono,  exportTable = T)
table_unique_clono$patient <- revalue(table_unique_clono$values, c("patient1_IP"="Patient 1", "patient1_Peak"="Patient 1", "patient2_IP"="Patient 2", "patient2_Peak"="Patient 2", "patient3_IP"="Patient 3", "patient3_Peak"="Patient 3", "patient4_IP"="Patient 4", "patient4_Peak"="Patient 4", "patient5_IP"="Patient 5", "patient5_Peak"="Patient 5" ))
table_unique_clono$patient <- factor(table_unique_clono$patient)
table_unique_clono$timepoint <- rep(c("IP","Peak"),5)

ggplot(table_unique_clono, aes(fill=values, y=contigs, x=patient)) + 
    geom_bar(position="dodge", stat="identity")+ scale_fill_manual(values=cols_patient2) +
  geom_text(aes(label=timepoint), position = position_dodge(width = .9), vjust = -0.3, color = "black") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
```


# Session Info

```{r}
sessionInfo()
```
